export const SUBMENU_OPEN = 'SUBMENU_OPEN';
export const TOGGLE_MAIN_SIDEBAR = 'TOGGLE_MAIN_SIDEBAR';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
export const NOTIFICATIONS = 'NOTIFICATIONS';
export const SIDEBAR_ACTIVITY = 'SIDEBAR_ACTIVITY';