export const SUBMENU_OPEN = 'SUBMENU_OPEN';
export const TOGGLE_MAIN_SIDEBAR = 'TOGGLE_MAIN_SIDEBAR';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';

export const NOTIFICATIONS = 'NOTIFICATIONS';
export const SIDEBAR_ACTIVITY = 'SIDEBAR_ACTIVITY';
export const RECENT_SALES = 'RECENT_SALES';
export const RECENT_SALES_BY_CHANEL = 'RECENT_SALES_BY_CHANEL';
export const GLOBAL_SEARCH_RESULTS = 'GLOBAL_SEARCH_RESULTS';
export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const BEST_SELLING_ITEMS = 'BEST_SELLING_ITEMS';
export const RECENT_BALANCE = 'RECENT_BALANCE';
export const USERS = 'USERS';
export const ADD_USER = 'ADD_USER';